name: 📊 Lines of Code Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Generate cloc report
        run: cloc --by-file --include-lang=JavaScript,HTML,CSS,Python . > cloc-report.txt

      - name: Update README with cloc stats
        uses: kencx/insert-text-action@v1
        with:
          file: README.md
          start: "<!-- START_SECTION:cloc -->"
          end: "<!-- END_SECTION:cloc -->"
          text: |
            ```txt
            $(cat cloc-report.txt)
            ```
