name: Generate Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity
          plugin_lines: yes
          plugin_lines_sections: total, yearly
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 3
